# Generated by Django 3.1.4 on 2021-01-13 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
