# Generated by Django 3.1.4 on 2021-02-04 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='media/noimage.png', upload_to=''),
        ),
    ]
