# Generated by Django 3.1.4 on 2020-12-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='has_days_times',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
