# Generated by Django 3.1.4 on 2020-12-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_class_has_days_times'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='has_days_times',
            new_name='is_saturdays',
        ),
        migrations.AddField(
            model_name='class',
            name='is_weekdays',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
