# Generated by Django 3.1.4 on 2021-01-04 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210101_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='day',
            new_name='class_day',
        ),
    ]
